---
- name: Inspect and Catalog Execution Environments
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    prune_images: true
    image_paths:
      - "registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8"
      - "registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9"
      - "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8"
      - "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9"
      - "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8"
      - "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9"
      - "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8"
      - "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9"
      - "registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8"
      - "registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9"
      - "registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9"
      # - "registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel10"
      - "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9"
      # - "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel10"
      - "registry.redhat.io/ansible-automation-platform-27/ee-minimal-rhel9"
      # - "registry.redhat.io/ansible-automation-platform-27/ee-minimal-rhel10"
      - "registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel9"
      # - "registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel10"
      - "registry.redhat.io/ansible-automation-platform-tech-preview/ee-minimal-rhel8"
      - "registry.redhat.io/ansible-automation-platform-tech-preview/ee-minimal-rhel9"

  roles:
    - role: image_inspector
      vars:
        image_inspector_image_paths: "{{ image_paths }}"
        image_inspector_prune_images: "{{ prune_images }}"
    # - role: md_generator
