# md_generator/tasks/main.yml
---
- name: "Ensure the output directory exists"
  ansible.builtin.file:
    path: "{{ md_generator_output_md_file | dirname }}"
    state: directory
    mode: '0755'

- name: Find all digest vars directories
  ansible.builtin.find:
    paths: "{{ md_generator_var_root_path }}"
    patterns: "vars"
    file_type: directory
    recurse: true
  register: vars_dirs

- name: Process each image path vars directory
  ansible.builtin.include_tasks: image_path_loop.yml
  loop: "{{ vars_dirs.files }}"
  loop_control:
    loop_var: __vars_dir
    label: "{{ __vars_dir.path }}"
